title: My Programming Journey 
email: pndaRN.dev@proton.me
description: >-
  Notes from learning to code as an adult
url: "https://pndarn.github.io"
baseurl: "/Programming-Journey"
github_username: pndaRN

theme: "just-the-docs"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

