title: My Programming Journey 
email: pndaRN.dev@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  Notes from learning to code as an adult
url: "https://pndarn.github.io"
baseurl: "/Programming-Journey"
github_username: pndaRN

# Build settings
remote_theme: just-the-docs/just-the-docs

just_the_docs:
  custom_css:
    - assets/css/custom.scss

plugins:
  - jekyll-feed
  - jekyll-remote-theme

