title: My Programming Journey 
email: pndaRN.dev@proton.me
description: >-
  Notes from learning to code as an adult
url: "https://pndarn.github.io"
baseurl: "/Programming-Journey"
github_username: pndaRN

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag

